v2/Cloudlab/Controllers/IDEController.cs
namespace Cloudlab.Controllers
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Web.Mvc;
    using Cloudlab.Helpers;
    using Cloudlab.Logic;
    using Cloudlab.Models;
    using Cloudlab.ViewModels;
    using DropNet;
    using DropNet.Exceptions;
    using System.Threading;

    [Authorize]
    public class IDEController : Controller
    {
        //public FileUploadJsonResult AjaxUpload(HttpPostedFileBase file)
        //{
        //    try
        //    {
        //        using (var reader = new BinaryReader(file.InputStream))
        //        {
        //            entities.Resources.AddObject(new Resource()
        //            {
        //                Created = DateTime.UtcNow,
        //                IsPublic = false,
        //                MimeType = file.ContentType,
        //                User = entities.Users.Single(u => u.Email == User.Identity.Name),
        //                Content = reader.ReadBytes(file.ContentLength),
        //                Filename = file.FileName,
        //                VirtualPath = "/"
        //            });
        //            entities.SaveChanges();
        //        }
        //        return new FileUploadJsonResult()
        //        {
        //            Data = new
        //            {
        //                message = string.Format("{0} uploaded successfully", System.IO.Path.GetFileName(file.FileName))
        //            }
        //        };
        //    }
        //    catch
        //    {
        //        return new FileUploadJsonResult()
        //        {
        //            Data = new
        //            {
        //                message = string.Format("{0} uploaded terribly", System.IO.Path.GetFileName(file.FileName))
        //            }
        //        };
        //    }
        //}

        public ActionResult PushEvent()
        {
            string response;
            while (!VMManager.FetchMessage(User.Identity.Name, out response))
            {
                Thread.Sleep(10);
            }
            /*if(!VMManager.FetchMessage(User.Identity.Name, out response))
            {
                return new HttpStatusCodeResult(200);
            }*/
            return Content(response);
        }

        #region Dropbox

        public JsonResult DropboxIsAuthorized()
        {
            return Json(Dropbox.IsAuthorized(User), JsonRequestBehavior.AllowGet);
        }

        public ActionResult DropboxDownload(string path, bool asBinary = false)
        {
            try
            {
                var dropbox = Dropbox.GetSession(User);
                if (asBinary)
                {
                    return new HttpStatusCodeResult(501);
                }
                else
                {
                    return Content(UTF8Encoding.UTF8.GetString(dropbox.GetFile(path)));
                }
            }
            catch (DropboxException ex)
            {
                ex.InnerException.SendToACP();
                return new HttpStatusCodeResult(404);
            }
            
        }

        

        public ActionResult DropboxListDir(string path = "/")
        {
            var dropbox = Dropbox.GetSession(User);
            var items = dropbox.GetMetaData(path);
            return Json(items.Contents, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DBAuth()
        {
            try
            {
                var client = Dropbox.GetSession();
                client.GetToken();
                var url = client.BuildAuthorizeUrl("http://cloudlab.apphb.com/IDE/DBAuthed/");
                Session["DropNetClient"] = client;
                return Json(url, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                e.SendToACP();
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult DBAuthed(long uid, string oauth_token)
        {
            if (!string.IsNullOrWhiteSpace(oauth_token))
            {
                try
                {
                    var client = (DropNetClient)Session["DropNetClient"];
                    Session.Remove("DropNetClient");
                    var accessToken = client.GetAccessToken();
                    using (var entities = new DatabaseEntities())
                    {
                        var user = entities.Users.Single(u => u.Email == User.Identity.Name);
                        user.DropboxSecret = accessToken.Secret;
                        user.DropboxToken = accessToken.Token;
                        entities.SaveChanges();
                    }
                }
                catch (Exception e)
                {
                    e.SendToACP();
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }              
            return View("~/Views/Main/Misc/DBAuthorizedView.cshtml");
        }

        #endregion

        #region Documentation

        public ActionResult DocList()
        {
            using (var entities = new DatabaseEntities())
            {
                var model = entities.JSEntities.OrderBy(d => d.Category).ThenBy(e => e.Entity).ThenBy(f => f.Name).ToList();
                return Json(new JSEntityIndexViewModel(model).Model, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Doc(int id)
        {
            using (var entities = new DatabaseEntities())
            {
                return Content(entities.JSEntities.Single(d => d.Id == id).Body);
            }
        }

        public ActionResult DocSearch(string q = "")
        {
            if(string.IsNullOrWhiteSpace(q))
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }


            using (var entities = new DatabaseEntities())
            {
                var terms = q.Split(new char[' '], StringSplitOptions.RemoveEmptyEntries).ToList();

                string firstTime = terms[0];
                var query = entities.JSEntities.Where(e => e.Body.Contains(firstTime))
                                               .ToList();

                for (int i = 1; i < terms.Count; i++)
                {
                    query = query.Where((a, b) => a.Body.Contains(terms[i])).ToList();
                }
                
                var jsonResults = query.Select(e => new
                {
                    id = e.Id,
                    category = e.Category,
                    entity = e.Entity,
                    name = e.Name,
                    type = e.Type
                });

                return Json(jsonResults, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region Account Actions

        public JsonResult APIInfo()
        {
            using (var entities = new DatabaseEntities())
            {
                var user = entities.Users.Single(u => u.Email == User.Identity.Name); 
                var model = new
                {
                    key = user.MasterKey,
                    credits = Account.API.APIQuota.Get(user.MasterKey.ToString())
                };
                return Json(model, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAPIPaymentLink(string sku)
        {
            var link  = "https://www.paymate.com/PayMate/ExpressPayment?";
                link += "mid=tristan@seditious-tech.com";
                link += "&currency=USD";
                link += "&pmt_sender_email=" + User.Identity.Name;
                link += "&return=http://cloudlab.apphb.com/main/PaymentReturned/";
                switch (sku) {
                    case "CLOUDLAB-API-1K":
                        link += "&amt=4.95&ref=CLOUDLAB-API-1K";
                        break;
                    case "CLOUDLAB-API-10K":
                        link += "amt=49.95&ref=CLOUDLAB-API-10K";
                        break;
                    case "CLOUDLAB-API-100K":
                        link += "&amt=149.95&ref=CLOUDLAB-API-100K";
                        break;
                }
                return Json(link, JsonRequestBehavior.AllowGet);
        }

        //public JsonResult AccountInfo()
        //{
        //    using (var entities = new DatabaseEntities())
        //    {
        //        var user = entities.Users.Single(u => u.Email == User.Identity.Name);
        //        var model = new {
        //            username = user.Email,
        //            created = user.Created,
        //            plan = user.ServiceLevel,
        //            expires = user.ServiceExpiration,
        //            contactable = user.IsContactable
        //        };
        //        return Json(model, JsonRequestBehavior.AllowGet);
        //    }
        //}

        #endregion
    }
}

v2/Cloudlab/Controllers/MainController.cs
namespace Cloudlab.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Security;
    using Cloudlab.Logic;
    using Cloudlab.Models;
    using NBrowserID;

    public class MainController : Controller
    {
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return View("Splash");
            }
        }

        [HttpPost]
        public ActionResult Authenticate(string assertion)
        {
            var authentication = new BrowserIDAuthentication();
            var verificationResult = authentication.Verify(assertion);
            if (verificationResult.IsVerified)
            {
                string email = verificationResult.Email;
                FormsAuthentication.SetAuthCookie(email, false);

                using (var entities = new Cloudlab.Models.DatabaseEntities())
                {
                    var user = entities.Users.SingleOrDefault(u => u.Email == email);
                    if (user == null)
                    {
                        entities.Users.AddObject(new Models.User()
                        {
                            Email = email,
                            IsContactable = false,
                            ServiceLevel = 0,
                            ServiceExpiration = DateTime.MaxValue,
                            Created = DateTime.UtcNow,
                            LastLogin = DateTime.UtcNow,
                            MasterKey = Guid.NewGuid()
                        });
                    }
                    else {
                        user.LastLogin = DateTime.UtcNow;
                    }
                    entities.SaveChanges();

                    /*user.APIKeys.Add(new APIKey() { Key = Guid.NewGuid(), ReadFlag = false, WriteFlag = false });
                    user.APIKeys.Add(new APIKey() { Key = Guid.NewGuid(), ReadFlag = true,  WriteFlag = false });
                    user.APIKeys.Add(new APIKey() { Key = Guid.NewGuid(), ReadFlag = false, WriteFlag = true  });
                    user.APIKeys.Add(new APIKey() { Key = Guid.NewGuid(), ReadFlag = true,  WriteFlag = true  });*/
                }

                //VMManager.AddUser(email);
                VMManager.AddOrReset(User.Identity.Name);
                return Json(new { email });
            }

            return Json(null);
        }

        public ActionResult Legal()
        {
            return View();
        }

        public ActionResult Exit()
        {
            Cloudlab.Logic.VMManager.Evict(User.Identity.Name);
            FormsAuthentication.SignOut();
            return Redirect("/");
        }

        [HttpPost]
        public ActionResult PaymentReturned(string transactionID, string responseCode, string paymentAmount,
                                            string currency, string paymentDate, string @ref, string buyerEmail,
                                            string billingAddress1, string billingAddress2, string billingCity,
                                            string billingState, string billingCountry, string billingPostcode, 
                                            string billingFirstName, string billingSurname)
        {
            
            //Response Code	Definition	Recommended Action
            //PP	Payment processing	Await email notification from Paymate prior to organising delivery of purchased items or service
            //PA	Payment approved	Proceed with organising delivery of items or provision of service immediately
            //PD	Payment declined	Contact buyer to organise another means of payment or discontinue order
            return View("PaymentReturned");
        }
    }
}

v2/Cloudlab/Views/Main/Modals/APIModal.cshtml
<div id="APIModal" class="modal hide fade in">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>Application Programming Interface</h3>
    </div>
    <div class="modal-body">
        <table id="T_APIModal" class="table table-bordered table-condensed"></table>
        <hr />
        <ul class="thumbnails" style="text-align:center; margin-left:10px">
            <li class="span2">
                <div class="thumbnail">
                    <div class="caption">
                    <h4>Hacker</h4>
                    <h5>1,000 Credits</h5>
                    <p><a data-purpose="purchase-credits" data-sku="CLOUDLAB-API-1K" class="btn btn-large" style="margin-top:15px;">$4.95</a></p>
                    </div>
                </div>
            </li>
            <li class="span2">
                <div class="thumbnail">
                    <div class="caption">
                    <h4>Developer</h4>
                    <h5>10,000 Credits</h5>
                    <p><a data-purpose="purchase-credits" data-sku="CLOUDLAB-API-10K" class="btn btn-large btn-info" style="margin-top:15px;">$49.95</a></p>
                    </div>
                </div>
            </li>
            <li class="span2">
                <div class="thumbnail">
                    <div class="caption">
                    <h4>Business</h4>
                    <h5>100,000 Credits</h5>
                    <p><a data-purpose="purchase-credits" data-sku="CLOUDLAB-API-100K" class="btn btn-large btn-primary" style="margin-top:15px;">$149.95</a></p>
                    </div>
                </div>
            </li>
        </ul>
        <p class="help-block">
            Payments are processed by <a href="http://paymate.com/" target="_blank">Paymate</a>. 
            Figures are in AUD, however other currencies are accepted.
            For more information on upgrades and payments, please refer to our 
            <a href="/Main/Legal/" target="_blank">legal section</a>.
        </p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-inverse" data-dismiss="modal">Close</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/AccountInfoModal.cshtml
<div id="AccountInfoModal" class="modal hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>Account Information</h3>
    </div>
    <div class="modal-body">
        <table id="T_AccountInfoModal"></table>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-inverse" data-dismiss="modal">Close</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/DropboxAuthModal.cshtml
<div id="DropboxAuthModal" class="modal hide fade in">
    <div class="modal-body">
        <div style="text-align:center">
            <img src="/Content/images/sync.png" />
        </div>
        <p>We want you to authorize Cloudlab! This will open up a separate window in 
           which you'll have to authorize cloudlab to access a specific folder in 
           your dropbox folder.</p>
    </div>
    <div class="modal-footer">
        <a class="btn btn-danger" data-dismiss="modal"><i class="icon-remove icon-white"></i> No Thanks</a>
        <a id="DropboxAuthModal_Authorize" class="btn btn-primary" data-dismiss="modal"><i class="icon-ok icon-white"></i> Authorize</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/DropboxDeAuthModal.cshtml
<div id="DropboxDeAuthModal" class="modal hide fade in">
    <div class="modal-body">
        <p>Are you sure you want Cloudlab to forget about your authorization?</p>
        <p class="help-block"></p>
    </div>
    <div class="modal-footer">
        <a class="btn btn-inverse" data-dismiss="modal"><i class="icon-remove icon-white"></i> Cancel</a>
        <a id="DropboxDeAuthModal_DeAuthorize" class="btn btn-danger" data-dismiss="modal"><i class="icon-ok icon-white"></i> Forget</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/DropboxInfoModal.cshtml
<div id="DropboxInfoModal" class="modal hide fade in">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times</a>
        <h3>Dropbox Account Info</h3>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="span3" style="width:270px">
                <table id="DropboxInfoModal_Table" class="table"></table>
                <p class="help-block">
                    This information is for your eyes only. 
                    We do not collect any of this information, nor will we 
                    disclose this information to third-parties.
                </p>
            </div>
            <div id="DropboxInfoModal_Graph" class="span3" style="height:200px">
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a class="btn btn-success" data-dismiss="modal">OK</a>
        <a class="btn btn-danger" data-dismiss="modal" id="DropboxInfoModal_Forget">Forget Account</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/FlattrModal.cshtml
<div id="FlattrModal" class="modal hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>Donations</h3>
    </div>
    <div class="modal-body">
        <div class="span5">
            <p>Cloudlab is still under development and until we get payments going. We'd really appreciate anything you care to provide!</p>
        </div>
            <a class="FlattrButton" style="display:none;" href="http://cloudlab.io"></a>
            <noscript>
                <a href="http://flattr.com/thing/583428/Cloudlab-Cloud-Computing-with-a-Programmable-API" target="_blank">
                    <img src="http://api.flattr.com/button/flattr-badge-large.png" alt="Flattr this" title="Flattr this" border="0" />
                </a>
            </noscript>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-inverse" data-dismiss="modal">Close</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/NewCollectionModal.cshtml
<div id="NewCollectionModal" class="modal hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>New Collection</h3>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="control-group">
                <label class="control-label" for="input01">Collection Name</label>
                <div class="controls">
                    <input type="text" class="input-xlarge " id="NewColectionModal_Name" />
                    <p class="help-block">Collections allow you to group related files together regardless of where they in the filesystem.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a class="btn" data-dismiss="modal">Cancel</a>
        <a class="btn btn-inverse" data-dismiss="modal" id="NewCollectionModal_CreateButton">Create</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/RevokeKeyModal.cshtml
<div id="RevokeKeyModal" class="modal hide fade in">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>Revoke API Key?</h3>
    </div>
    <div class="modal-body">
        <p>Revoking your API Key will discard your current key and replace it with a new one. This operation is irreversible. Are you sure you want to revoke your key?</p>
        <p class="help-block">This operation does not increase/decrease your account quota.</p>
    </div>
    <div class="modal-footer">
        <a class="btn btn-inverse" data-dismiss="modal"><i class="icon-remove icon-white"></i> Cancel</a>
        <a class="btn btn-danger"  data-dismiss="modal" id="RevokeKeyModal_RevokeButton"><i class="icon-ok     icon-white"></i> Revoke</a>
    </div>
</div>

v2/Cloudlab/Views/Main/Modals/UploadFileModal.cshtml
<form id="resourceUploadForm" method="post" action="@Url.Action("AjaxUpload", "IDE")" enctype="multipart/form-data">
    <div id="UploadFileModal" class="modal hide fade">
        <div class="modal-header">
            <a class="close" data-dismiss="modal">&times</a>
            <h3>Upload Resource</h3>
        </div>
        <div class="modal-body">
            <input name="file" type="file" />
        </div>
        <div class="modal-footer">
            <a class="btn" data-dismiss="modal">Close</a>
            <input id="ajaxUploadButton" type="submit" value="Submit" class="btn btn-primary"  />
        </div>
    </div>
</form>